### ISSUE TITLE
Add models to the Fabrik Model Zoo

### ISSUE THREAD

**Issue by utsavgarg** [Cloud-CV/Fabrik#105]
We want to make the Fabrik ModelZoo a rich collection of models from all streams of deep learning research (vision, speech, text) and want to add models from both frameworks that are currently well supported by this project (Caffe and Keras).

For people looking to get started with contributing to this project, this is a very good starting point. To add a model to the model zoo, please do the following:
- Add the model prototxt/json to the `example/<framwork>` folder depending on the model being from caffe or keras
- Add the entry to the models drop-down list on the front-end 
- Test if loading the model and exporting it to both or at least one framework is working fine

**Comment by utsavgarg** [comment]
@melvyniandrag we currently have some issue with Keras depenencies on the deplyed version which is why you might be facing problems in loading some models. I am not quite sure about the wrapping idea, if you could come up with a mock-up we can then discuss it further.

**Comment by melvyniandrag** [comment]
I guess this ties into the issue with the docker containers too? I guess I'll work on this in a container and then if no one has made one yet Ill submit the docker file too.

**Comment by deshraj** [comment]
@melvyniandrag: Sounds good. This is super critical so it would be great if you can submit the pull request really soon.

**Comment by manuhortet** [comment]
Hello, I'm trying to add some models to the Fabrik ModelZoo. I've added the prototxts to the right `example/framework` folder and did the right calls from `ide/static/bundle/bundle.js`

The added models do appear in Actions > Load from zoo, but when I click them, nothing happens. No error message appears, so I'm not pretty sure what's going wrong. Any help here?

**Comment by AtharvaKhare** [comment]
@manuhortet I think you need to modify `ide/static/js/topBar.js`. `ide/static/bundle/bundle.js` is generated by webpack.

Also, are you keeping your models in `example/keras` or `example/caffe`?

**Comment by manuhortet** [comment]
I did what you suggested but it doesn't seem to work either. I'm keeping my models in example/caffe, as I got them from the Caffe ModelZoo and are `.prototxt` files.

I found this comment on `netLayout.js`: 

```
// designed to work with googleNet.
// will work with all prototxts which follows our assumption
// but the UI may not be clean.
```

Maybe I'm trying to load invalid prototxt files? Btw thank you for your help Atharva!

**Comment by utsavgarg** [comment]
@manuhortet if the prototxt files are invalid, an error should pop up. In case its not clear to add a model to the model zoo for Caffe you have to do the two following things:
1. Add the prototxt file in `example/caffe`
2. add a line like `<li><ModelElement importNet={this.props.importNet} framework="caffe" id="alexnet">AlexNet</ModelElement></li>` to `topbar.js`, in this the id should be the name of your prototxt without the extension.
After making these changes, you will need to run webpack and then the file should load.

**Comment by Shivanshmundra** [comment]
@utsavgarg What is the progress in this issue?
What are things left to done or to start, I would like to take this issue.
