### ISSUE TITLE
Cannot Export GoogLeNet into Keras

### ISSUE THREAD

**Issue by nickeleres** [Cloud-CV/Fabrik#110]
Trying to export GoogLeNet from the "Model Zoo" dropdown at the URL below:

http://fabrik.cloudcv.org/#/?_k=ngzknm

And Im getting the error, "Cannot convert LRN to Keras" [see attached].  Im guessing this is because the LRN regularization layer doesnt have an associated entity in Keras.

![image](https://user-images.githubusercontent.com/3239870/30839347-2a76f026-a226-11e7-999b-e9513ba78310.png)

**Comment by utsavgarg** [comment]
@nickeleres as Keras does not have an LRN layer, it's not possible to export GoogLeNet to Keras.

**Comment by nickeleres** [comment]
A more descriptive error message would be helpful.  I checked the browser console and it was throwing a server error, so the error is clearly not handled/expected in the core code's exceptions.

**Comment by nickeleres** [comment]
Im getting the attached 500s when attempting to export VGG 16 to Keras, as well.

![image](https://user-images.githubusercontent.com/3239870/30841916-8b2eed26-a233-11e7-8acd-970d86f61d86.png)

**Comment by virajprabhu** [comment]
@nickeleres Thanks for pointing this out. Agreed, we shouldn't be throwing an error. Will need to look into a fix.

**Comment by utsavgarg** [comment]
@nickeleres the deployed version is now fixed, you should be able to export VGG-16 to Keras.
