### ISSUE TITLE
[UI/UX] Not easy to know if Fabrik is exporting model or not

### ISSUE THREAD

**Issue by YuChunLOL** [Cloud-CV/Fabrik#111]
I suggest that when the user clicks the "export" button, the system will show a dialog
or some other UI components which is easy to seize the user's attention. Since the position of "progress circle" is assigned to the top-right which is not very intuitive for the users, I think this design is not very well. Also, if the "progress circle" can show the progress to the user, it will be better.

**Comment by virajprabhu** [comment]
@YuChunLOL Yes, that might be a nice feature to have. Let me know if you'd like to work on this.

**Comment by Ram81** [comment]
@virajprabhu can I work on this?

**Comment by virajprabhu** [comment]
@Ram81 We haven't heard back from @YuChunLOL, so feel free to work on this.

**Comment by Ram81** [comment]
@virajprabhu in case of loader, should I fade the rest of UI until the model gets loaded& bring the loader to center of screen, what do you say

**Comment by utsavgarg** [comment]
Fixed in #152
