### ISSUE TITLE
Document whether this tool can be used for text

### ISSUE THREAD

**Issue by alexanderkjeldaas** [Cloud-CV/Fabrik#113]
Thanks for this tool!

Could you put a section outlining what is in-scope and out-of-scope in the README?

It's unclear to me for example whether I can use this to create LSTMs, seq2seq, or in general handle text.

Also what the input to the models are, i.e. what plumbing is required when I have the output from the tool in order to get data in and out from the model would be good to outline in the README.

**Comment by virajprabhu** [comment]
@alexanderkjeldaas Thanks for pointing this out, we do need to add details for how one can plug output from Fabrik into your code. To answer your question, we can support any input datatype the underlying framework support.

**Comment by virajprabhu** [comment]
Covered by #116.
