### ISSUE TITLE
Add RNN / LSTM examples for Keras in ModelZoo

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Fabrik#115]
Keras supports recurrent layers like LSTM / RNN / GRU etc. Right now model zoo for Fabrik doesn't contain any examples of network that uses these layers. 

We should add a few examples to demonstrate the capability of using recurrent layers in a network and to test how import / export works for these layers.

**Comment by Ram81** [comment]
@dexter1691 can I take this?

**Comment by dexter1691** [comment]
@Ram81 : Go for it! Thanks!

**Comment by prakharchoudhary** [comment]
@dexter1691 Since there are multiple models from several domains that can be added, would it be okay for me to work on this issue as well?

**Comment by dexter1691** [comment]
@prakharchoudhary Ofcourse! Feel free to work on it. I think to ensure efforts are not duplicated, before working on adding the examples, mention the model here so that everyone is aware of it.

**Comment by Ram81** [comment]
@dexter1691 can you point us to some of the models!

**Comment by utsavgarg** [comment]
@Ram81 you could look at Captioning models (Show and Tell, Neuraltalk), VQA models, and Text generation models.

**Comment by Ram81** [comment]
@utsavgarg I am referring this one https://github.com/jeffdonahue/caffe/blob/recurrent-rebase-cleanup/examples/coco_caption/lstm_language_model.prototxt as of now but I would need keras models right?

**Comment by Ram81** [comment]
@utsavgarg would it be fine if I export this model https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py to json then use it as an example?

**Comment by utsavgarg** [comment]
@Ram81 you could do it in Caffe or Keras, but choose one out of these two as they are quite similar.

**Comment by Ram81** [comment]
@utsavgarg I used this model https://github.com/jeffdonahue/caffe/blob/recurrent-rebase-cleanup/examples/coco_caption/lstm_language_model.prototxt  & tested it in here's the model

![lstm](https://user-images.githubusercontent.com/16323427/30950585-791ce8fe-a43b-11e7-8530-0e0029e4848b.png)
 But when I tried to export it to keras it says Can't determine size of HD5Data layer

**Comment by Ram81** [comment]
Also there are some examples available but I would need to obtain a json file through its implementation if you want I can test them too.

**Comment by utsavgarg** [comment]
@Ram81 When you are adding this network, can you also see how to handle the visualization for it better? Also, the error for export to Keras is expected so that is fine.

**Comment by Ram81** [comment]
@utsavgarg Okay I will take care of the visualization.

**Comment by dexter1691** [comment]
I think we should also try just importing Keras layers with recurrent layers too. That might be easier / more reliable since Keras's support for recurrent layer is much better than caffe. 
For instance, you can try importing model definition from here: https://github.com/fchollet/deep-learning-models/blob/master/music_tagger_crnn.py

**Comment by Ram81** [comment]
@dexter1691 I would need to export that keras model to a json file, right?

**Comment by utsavgarg** [comment]
@ram81 yes

**Comment by Ram81** [comment]
@utsavgarg I will create a PR for this model & start with adding examples for keras too.

**Comment by valkyrie-101** [comment]
@dexter1691 , is it ok if I work on it too? Correct me if I'm wrong, but more examples will do no harm.

**Comment by utsavgarg** [comment]
Multiple examples added in #125 #134 #140 and #166
