### ISSUE TITLE
Add documentation on plugging output from Fabrik into code 

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/Fabrik#116]
Minimum: We need to write documentation how you can plug the model config file generated from Fabrik into your code.

Stretch: We should write a wrapper function that does this, and add it to our documentation.

**Comment by Insaida** [comment]
I could work on this.

**Comment by AtharvaKhare** [comment]
@Insaida are you working on this?

**Comment by utsavgarg** [comment]
Initial documentation added in #173

**Comment by utsavgarg** [comment]
Added in #173, #216, #224 and #246
