### ISSUE TITLE
Add a title pane

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/Fabrik#117]
We should add a title pane with the model name – this should be an editable field which:
* defaults to untitled if the user is building a model from scratch
* takes the name of whatever the model file is called if loading from zoo / importing from any framework
* Should go into DB – when a shared link is opened, the same name should show up.

**Comment by hd719** [comment]
Hey can I work on this?

**Comment by virajprabhu** [comment]
Absolutely, go ahead! Let us know if you have questions.

**Comment by viveksyngh** [comment]
Is anyone working on this one ?

**Comment by deshraj** [comment]
I don't think so. Feel free to work on it.

**Comment by viveksyngh** [comment]
@deshraj  I have few questions. Where this title field will be added in UI and if it needs to save to DB is there already existing model in which I can add this filed or I need to create a new model ?

**Comment by virajprabhu** [comment]
Adding it on the top would be fine. And yes, we should save it to DB. @utsavgarg might be able to point you to the right model.

**Comment by utsavgarg** [comment]
@viveksyngh the models are saved as a JSON object in the database which already has a `net_name` field so you don't need to change any model but just have to make a UI for displaying and changing that field.

**Comment by viveksyngh** [comment]
When I tried to run the app in local(ubuntu 14.04) by following the instructions in readme file .. I am getting below error ..
```
ImportError: No module named caffe.proto
```

**Comment by utsavgarg** [comment]
@viveksyngh you can check the chat on Gitter for installation problems.

**Comment by AtharvaKhare** [comment]
@viveksyngh 
```
export PYTHONPATH=$PYTHONPATH:$HOME/caffe/caffe/python
```

**Comment by manuhortet** [comment]
add the line @AtharvaKhare commented to your ./bashrc and source it (just run `source ./bashrc`), problem will be solved.

**Comment by viveksyngh** [comment]
Even after doing that I am getting same error

**Comment by suraj44** [comment]
Is anyone working on this issue?

**Comment by utsavgarg** [comment]
@viveksyngh are you working on this?

**Comment by viveksyngh** [comment]
I was working on this one but I was not able to setup environment due to error. I was quite busy this week so couldn't continue. Try to setup the environment and work on this over weekend.

**Comment by utsavgarg** [comment]
Added in #185
