### ISSUE TITLE
Unable to import json file of keras models

### ISSUE THREAD

**Issue by prakharchoudhary** [Cloud-CV/Fabrik#122]
When importing the json file of a keras model, the API throws a `ValueError`. There seems to be some trouble in loading the JSON data in the correct format. Following is a screen-shot of the error log:
![json_import](https://user-images.githubusercontent.com/15031548/31039911-6abf4a44-a59f-11e7-96a7-50a8db2a7df4.png)

**Comment by prakharchoudhary** [comment]
@dexter1691 Thanks for the green flag to this issue. I will try to fix it ASAP so that we can continue with adding the models suggested in issues #115 and #118.

**Comment by Ram81** [comment]
@prakharchoudhary I tried importing keras models & it works for me.

**Comment by prakharchoudhary** [comment]
@Ram81 Well this is surprising. What model did you import? Can you share the json file?

**Comment by dexter1691** [comment]
@prakharchoudhary : Can you also share the JSON file you were trying to import so that we can further debug?

**Comment by prakharchoudhary** [comment]
@dexter1691 The JSON file to replicate this error is [vqa_lstm.zip](https://github.com/Cloud-CV/Fabrik/files/1346381/vqa_lstm.zip). This model was can be found at the link suggested by you at:
https://github.com/avisingh599/visual-qa/blob/master/models/lstm_1_num_hidden_units_lstm_512_num_hidden_units_mlp_1024_num_hidden_layers_mlp_3.json

**Comment by utsavgarg** [comment]
@prakharchoudhary closing this. Please see comment in #118.
