### ISSUE TITLE
Display parameters of the model being visualized

### ISSUE THREAD

**Issue by utsavgarg** [Cloud-CV/Fabrik#126]
We should display the number of parameters(weights of the model) the model contains somewhere on the screen. These parameter values should change whenever a new layer is added or some existing layer is changed.

**Comment by gpowale** [comment]
You can assign this to me, I can get started on this issue :)

**Comment by utsavgarg** [comment]
@gpowale sure go ahead.

**Comment by ayush1999** [comment]
@utsavgarg @RishabhJain2018  Can I take up this issue? Please help me in getting started.

**Comment by deshraj** [comment]
@ayush1999 please go ahead. We haven't heard from @gpowale for last 12 days.

**Comment by ayush1999** [comment]
Thanks @deskraj . Can you please tell me how can I solve this? Just a little background.

**Comment by utsavgarg** [comment]
@ayush1999 you will have to calculate the number of parameters when a model is imported which should be simple as you can calculate the size of the weight and bias matrices. And then whenever a layer is added or deleted you add or subtract its parameters from the total count.

**Comment by Ram81** [comment]
@utsavgarg can I take this?

**Comment by utsavgarg** [comment]
@Ram81 I'd recommend working on one issue at a time so that it's not blocked for others, so please finish #127 first as you had expressed interest in it and if still there is no update from @ayush1999 you can work on this.

**Comment by Ram81** [comment]
@utsavgarg Sure

**Comment by Ram81** [comment]
@utsavgarg can I start with this one now?

**Comment by utsavgarg** [comment]
@Ram81 Sure.

**Comment by kurianbenoy** [comment]
Is this issue fixed or can someone take it up?

**Comment by Ram81** [comment]
@kurianbenoy I am currently working on it.
