### ISSUE TITLE
Handle visualization of models having different arrangement for Test, Train phases.

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/Fabrik#127]
![test](https://user-images.githubusercontent.com/16323427/31188698-68e79aca-a953-11e7-95f1-cee87916db0e.png)
Test Model
![train](https://user-images.githubusercontent.com/16323427/31188714-7415302e-a953-11e7-89aa-e8a94cb52ce0.png)
Train Model

**Comment by Ram81** [comment]
@utsavgarg I will start working on this :smiley:

**Comment by Ram81** [comment]
@utsavgarg Any suggestions on this?

**Comment by adityaXXX** [comment]
@utsavgarg Can I contribute by solving this issue?

**Comment by Ram81** [comment]
@adityaXXX I am currently looking into various problems for this issue, can you please look for some other issue!
