### ISSUE TITLE
thereis not bundle.js

### ISSUE THREAD

**Issue by vhp1360** [Cloud-CV/Fabrik#159]
Hello guys,
I finally installed _Fabrik_ but when try to browse it, I encountered blank page:
![image](https://user-images.githubusercontent.com/11258052/33524223-88e6f984-d82d-11e7-9851-0bfe77c5167c.png)
and when I tried to find _bundle.js_, there is not bundle folder in _./idle/static_ path.
> css  fonts  img  js  lib

what should I do?

**Comment by JPJPJPOPOP** [comment]
@vhp1360 You need to run webpack --progress --watch --colors.
