### ISSUE TITLE
Layer boxes UI Enhancements

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/Fabrik#16]
It would be nice to show layer details on hover (instead of the user having to click the layer box) - [this](http://ethereon.github.io/netscope/#/preset/caffenet) is a nice example. 

No border and border-radius for boxes also seems to look nicer.

**Comment by anweshknayak** [comment]
could you provide some hint ?

**Comment by virajprabhu** [comment]
@anweshknayak Updated the description. Does it make more sense now?

**Comment by virajprabhu** [comment]
@anweshknayak Any update on this? Do you want to take this up?

**Comment by anweshknayak** [comment]
@virajprabhu yup.

**Comment by virajprabhu** [comment]
Great. Let me know if you need help.

**Comment by anweshknayak** [comment]
@virajprabhu can you create something like this (https://github.com/Cloud-CV/CloudCV/blob/master/DirectoryDocumentation.txt) Will be helpful for newcomers

**Comment by utsavgarg** [comment]
@virajprabhu I was looking at this issue, but when I make changes to the style.css file they don't reflect in the web interface, is there any other file I need to modify to reflect those changes ?

**Comment by virajprabhu** [comment]
@utsavgarg  That should work. Did you run webpack with watch / rebuild the bundle and refresh the page ignoring cache?

**Comment by utsavgarg** [comment]
@virajprabhu yeah it did work, I was not running `python manage.py collectstatic`

**Comment by utsavgarg** [comment]
@virajprabhu I have also added support for tool-tips on hover so all issues in this thread are addressed.

![screenshot from 2017-03-12 23-18-15](https://cloud.githubusercontent.com/assets/11680179/23834523/c7e07ba0-077d-11e7-9d3c-c8a6b3cdf780.png)
![screenshot from 2017-03-12 23-18-26](https://cloud.githubusercontent.com/assets/11680179/23834524/c9e4f7e6-077d-11e7-853a-f4f0ae9dadeb.png)

**Comment by virajprabhu** [comment]
Looks good, thanks!

**Comment by utsavgarg** [comment]
@virajprabhu yes I have.

**Comment by RAHULVAMUSANI** [comment]
Hey @virajprabhu  i would like to develop the user experience . what are the steps should i follow for assigning the task to me?

**Comment by virajprabhu** [comment]
Fixed in #67
