### ISSUE TITLE
Model Sharing

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/Fabrik#17]
We want to have a feature to generate a shareable link to a network built by a user that another user can view, edit. We will need to store the link and prototxt in our database when the user clicks share, and look up and regenerate the network from DB when another user tries to access the link.

Eventually we want to also allow collaborative editing of networks with real time updates.

@deshraj @dexter1691.

**Comment by souravsingh** [comment]
I would like to work on the issue. How do I get started?

**Comment by deshraj** [comment]
@souravsingh sorry for replying late. I missed this thread somehow. You can start with the integration of django-allauth and then after setting up the authentication, we can work on generating the sharable link as a new feature. Does that sound good?

**Comment by souravsingh** [comment]
@deshraj Thanks, I will start working on it.

**Comment by jainamritanshu** [comment]
@deshraj @virajprabhu Can I work on this issue if it's still open and not assigned to anyone else?

**Comment by virajprabhu** [comment]
@jainamritanshu This has not been assigned yet, but I'd recommend you take on one issue at a time so as to not block others. I'd recommend starting with #14 that you expressed interest in, since that is a simpler issue to get started with.

**Comment by utsavgarg** [comment]
@virajprabhu I have added support for static model sharing, the flow of events is as follows:

- export prototxt to url, a unique id will be given and the prototxt will be saved on the server
- import prototxt from url, enter the generated id, and the prototxt will load

![output_e6v7ot](https://cloud.githubusercontent.com/assets/11680179/24166551/9f242c48-0e99-11e7-9838-3fab567678e1.gif)
