### ISSUE TITLE
Export fails after layer is added

### ISSUE THREAD

**Issue by utsavgarg** [Cloud-CV/Fabrik#184]
Export fails if a new layer is added to a model that has been loaded from the Fabrik model zoo.
Steps to recreate:
-  Load YoloNet from the Fabrik model zoo
- Add a Softmax loss layer
- Click on export to Caffe

**Comment by Ram81** [comment]
@utsavgarg I guess I know why this is happening

**Comment by NSDCars5** [comment]
I have a fix that's working to some extent - prototxt files are being generated. Is this enough or do we have to somehow check their validity? If so, how?

**Comment by PalashTanejaPro** [comment]
@NSDCars5 You can check their validity by importing them through Fabrik again! 
Or you can write a script that uses that prototxt to construct a model
