### ISSUE TITLE
Collapsibles' arrow in the sidebar can get unsynchronized

### ISSUE THREAD

**Issue by adamstafa** [Cloud-CV/Fabrik#188]
When you press an arrow twice, or you have expanded one category in the sidebar and expand another category, the arrows will get unsynchronized.

**Comment by trexdinosaur** [comment]
Did you end up fixing this? In #176, I added the expansion to work on the whole row, but it doesn't fix this. However, this seems to be a very edge case it doesn't seem very likely this would happen, unless the user is really frustrated and just mashing the arrow button.

**Comment by adamstafa** [comment]
@trexdinosaur Yeah, this worked for me: #189. It also happened when you had one tab open and opened another.

**Comment by trexdinosaur** [comment]
Ahh I see, that does work! Thanks. There should be no conflicts with #176

**Comment by adamstafa** [comment]
@trexdinosaur actually my PR relies on `this.toggleClass(...)` that you removed in your PR 😀. The method can be called anywhere tho, so this won't be any hard-to-fix issue

**Comment by adamstafa** [comment]
Ahhh nvm, you just moved the listeners to the parent divs lol. This won't cause any problems! :smile:

**Comment by utsavgarg** [comment]
Fixed in #189
