### ISSUE TITLE
Visualization is broken

### ISSUE THREAD

**Issue by adamstafa** [Cloud-CV/Fabrik#191]
The visualization algorithm is doing really fancy stuff when 2 layers are distant from each other. When they are close enough, there's no problem.
![image](https://user-images.githubusercontent.com/34075272/34116876-24a767b2-e41a-11e7-88d3-7326a8c62973.png)

**Comment by trexdinosaur** [comment]
#186 adds an even more complicated algorithm to fix this issue, it's working, but not clean enough to merge yet. 

It should be ready in like a day if there are no major bugs :)

Thanks.

**Comment by trexdinosaur** [comment]
#186 has been merged, so the issue should be fixed @adamstafa. If it is please go ahead and close the issue :)

**Comment by adamstafa** [comment]
@trexdinosaur sure, closing
