### ISSUE TITLE
Fabrik Doesn't work on Edge

### ISSUE THREAD

**Issue by trexdinosaur** [Cloud-CV/Fabrik#198]
Fabrik doesn't seem to be working on the latest version of edge. Seems to be an issue w/ jsplumb.

As a temporary fix, can I add a message that says please use Google Chrome to access Fabrik?

**Comment by PalashTanejaPro** [comment]
@trexdinosaur Let me confirm that

**Comment by NSDCars5** [comment]
This seems to be related to this: https://stackoverflow.com/questions/11927309/html5-dnd-datatransfer-setdata-or-getdata-not-working-in-every-browser-except-fi

I replaced e.dataTransfer with a state variable in content.js and now drag drop works, as well as importing from the model zoo.

![Edge works](https://user-images.githubusercontent.com/5107795/34147072-6b4905f6-e4c2-11e7-99a9-8db32d6bd28f.JPG)
