### ISSUE TITLE
GOOGLE CODE IN RISHABH JAIN (wrong position of layers)

### ISSUE THREAD

**Issue by rishabhjain2807** [Cloud-CV/Fabrik#218]
Add a few layers, distance them such that you have to scroll to see all of them.

Scroll down, and add a layer by dragging and dropping.

Expected outcome: Layer is added where you dropped it.

outcome: Layer is added somewhere near the top of the canvas, where you have to scroll up to see it.

**Comment by virajprabhu** [comment]
Thanks @RishabhJain2018. This does look like a minor bug. If you'd like to look into a possible fix, let me know and I could assign you.

**Comment by utsavgarg** [comment]
I think this was already fixed in #204
