### ISSUE TITLE
Current Visualisation algorithm breaks for more than 4 layers in one horizontal line

### ISSUE THREAD

**Issue by PalashTanejaPro** [Cloud-CV/Fabrik#241]
![image](https://user-images.githubusercontent.com/22736920/34527006-108efcf6-f0ca-11e7-85f9-9f427b5b1bae.png)
Steps to reproduce:- 
- Create more than 4 layers in one horizontal line.
- Add layers below that row and try connecting it with a layer above the row. 

Expected behavior in the given screenshot:
- There are paths that can be taken from in between the two nodes.
- It can also take paths from the left.

**Comment by utsavgarg** [comment]
@PalashTanejaPro I am not sure if any model has this many layers in parallel if you can find an example we can then look at a possible fix.

**Comment by trexdinosaur** [comment]
@PalashTanejaPro I think this is a bug w/ the viz algo, can you give me a json file, so I can replicate and fix?

**Comment by utsavgarg** [comment]
Closing this as it doesn't seem to be a common use case.
