### ISSUE TITLE
Error When Importing relu6

### ISSUE THREAD

**Issue by galiaxy** [Cloud-CV/Fabrik#268]
When I import a json file that contains a relu6 layer, it returns this error:
`ValueError: Unknown activation function:relu6`

Visually, relu6 just the same as relu. It's just sort of a copy of relu with some changes, so it (probably) won't be that hard to implement.

**Comment by utsavgarg** [comment]
`relu6` seems to be a slight modification of `relu` with a upper cut-off at 6, it is available in Tensorflow but doesn't seem to be available in Keras by default, so I am not sure if we can directly add support for it,

**Comment by galiaxy** [comment]
Alright. Should I close this issue then?
