### ISSUE TITLE
Nondescript 'dim' error when adding certain data layers

### ISSUE THREAD

**Issue by namansood** [Cloud-CV/Fabrik#285]
- **Steps to reproduce the problem:** add an ImageData, Data, HD5Data, WindowData or MemoryData layer.

- **The expected behaviour:** Layer is added without incident.
- **The observed behaviour:** Error that says 'dim', and nothing else. [Example.](https://i.imgur.com/fcMSAsG.mp4)

This seems to be an issue with the backend, can I work on this?

**Comment by PalashTanejaPro** [comment]
@NSDCars5 I successfully reproduced the issue but **is it a backend issue?** I see no requests being made to the backend whatsover.

**Comment by NSDCars5** [comment]
@PalashTanejaPro There's a request made to /layer_parameter in updateLayerShape() in content.js, which sends back this error.

![screenshot_2018-01-17_19-36-49](https://user-images.githubusercontent.com/5107795/35046771-fbf74e5c-fbbd-11e7-875a-2537f42f0f1d.png)

**Comment by PalashTanejaPro** [comment]
@NSDCars5 oh ok, this part of Fabrik was changed pretty recently. 
This bug **might** have been introduced then.

**Comment by NSDCars5** [comment]
@PalashTanejaPro Yeah. I think I fixed the issue, waiting for a response from a maintainer to open a PR.

**Comment by Ram81** [comment]
@NSDCars5 this issue is because of shape calculation logic for any layer, do you want to handle this or should I do it ?

**Comment by NSDCars5** [comment]
@Ram81 I'd like to attempt it as a learning experience. Would it be okay if I made the PR and you can tell me if I mess anything up?

**Comment by Ram81** [comment]
@NSDCars5 sure go ahead & let me know in case of doubts

**Comment by MuLx10** [comment]
@NSDCars5  @Ram81 @PalashTanejaPro Has the issue been solved?Can I take up this issue?

**Comment by Ram81** [comment]
@MuLx10 Yeah it has been fixed
