### ISSUE TITLE
Import all the models from Caffe ModelZoo into IDE

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Fabrik#30]
We should try to successfully import all the models from Caffe ModelZoo to see if some layers are not working. 
Consequently fix or add the missing the layers into the IDE. 

https://github.com/BVLC/caffe/wiki/Model-Zoo

For GSOC participants:
This seems like a very good starting point to see how IDE works. Here is what you have to do
- Choose one of the models from the link above and create an issue for it. Cross reference it here for others to see.
- We will assign the issue to you
- If the model is working. Add a unit test for it so that any later changes to the projects ensure compatibility with those models. 
- If the model isn't working, try to discuss with the mentors and fix the issue! 

We are maintaining the list of models tested by contributors here: 
https://github.com/Cloud-CV/IDE/wiki/Models

**Comment by anweshknayak** [comment]
https://gist.github.com/jimmie33/7ea9f8ac0da259866b854460f4526034

This is working for me. @dexter1691 

![screenshot from 2017-02-12 02 16 02](https://cloud.githubusercontent.com/assets/8139783/22857343/7757562e-f0c9-11e6-83f8-ffbceb7ce64e.png)
![screenshot from 2017-02-12 02 15 47](https://cloud.githubusercontent.com/assets/8139783/22857345/7ab13bc8-f0c9-11e6-82a5-0f1ef9a9414a.png)

**Comment by dexter1691** [comment]
Nice! Let's maintain a list of the one's that working and the ones that are not working. GoogleNet was already part of the ones that we used to check. 

Let's keep trying others to find out the ones that are not working. I am sure there will be a few!

**Comment by anweshknayak** [comment]
https://gist.github.com/jimgoo/0179e52305ca768a601f Not working.

**Comment by kris-singh** [comment]
I woul like to work on this

**Comment by virajprabhu** [comment]
@anweshknayak Are you sure we have front-end support for all the layers in the prototxt?

@kris-singh Great, can you start with simple classification models like AlexNet and VGGNet? Would be great if you could try out a ResNet (it won't work at the moment) and open an issue with the layers that we are missing. It would also help you a good overall idea of the current status of the project.

**Comment by Ram81** [comment]
@virajprabhu  I am interested in this one can you guide me?

**Comment by virajprabhu** [comment]
@Ram81 Great. Have you set up IDE and tried importing the example prototxt file for GoogLenet? We similarly want to be able to import a wide variety of prototxt files from the Caffe [Model Zoo](https://github.com/BVLC/caffe/wiki/Model-Zoo). For that, we may need to add front-end support for more Caffe layers. As a concrete starting point, can you try importing classification CNN models like AlexNet / VGGNet / ResNet and verify that they work (by commenting on this thread) / identify which layers are missing and open an issue for the same?

**Comment by Ram81** [comment]
@virajprabhu sure I will setup IDE and let you know if I need some help :+1:

**Comment by utsavgarg** [comment]
@virajprabhu I am also interested in trying out classification networks if any hasn't been implemented yet

**Comment by utsavgarg** [comment]
@dexter1691 
AlexNet from Caffe Model Zoo loads fine, but the 'Group' parameters present in conv layers are ignored.
https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/deploy.prototxt 
![alexnet](https://cloud.githubusercontent.com/assets/11680179/23621060/339ff280-02bf-11e7-9a83-480f731c57ee.png)
VGG-16 present in Caffe Model Zoo is for an older Caffe version, I updated the prototxt to support the newer Caffe version and it loads fine now.
https://gist.github.com/utsavgarg/e3982498e9fb27d882cf877e7992ec9b
![vgg](https://cloud.githubusercontent.com/assets/11680179/23621208/c7dd46aa-02bf-11e7-8895-40c22e438dbd.png)

**Comment by Omarito2412** [comment]
[Squeezenet](https://github.com/BVLC/caffe/wiki/Model-Zoo#squeezenet-alexnet-level-accuracy-with-50x-fewer-parameters)

![squeeze](https://cloud.githubusercontent.com/assets/4267096/23623801/0b906e2c-02ac-11e7-90dd-04f480c23952.PNG)

**Comment by Omarito2412** [comment]
[RCNN](https://github.com/BVLC/caffe/wiki/Model-Zoo#faster-r-cnn-towards-real-time-object-detection-with-region-proposal-networks)
![2](https://cloud.githubusercontent.com/assets/4267096/23624253/d0f542c2-02ad-11e7-9795-a23f2f5d48e5.png)

**Comment by utsavgarg** [comment]
[Network in Network](https://gist.github.com/utsavgarg/37262bb660fd76801af1d098c95ab978)
![nin](https://cloud.githubusercontent.com/assets/11680179/23638808/d52ed130-0309-11e7-9dd9-95374137ab20.png)

**Comment by virajprabhu** [comment]
@utsavgarg @Omarito2412 Thanks for reporting these, and opening issues for the ones that don't work! If you would like to work on adding support to any of the ones that don't work, post on the issue thread and I'll assign it to you. Feel free to ping the Gitter channel / comment if you need any help setting up or would like to discuss the implementation.

**Comment by Omarito2412** [comment]
@virajprabhu I would like to work on adding support for S2VT network #36

**Comment by virajprabhu** [comment]
@Omarito2412 Sounds good. Please go ahead, and let me know if you need help.

**Comment by Ram81** [comment]
@virajprabhu which one should I try can you suggest one?

**Comment by prasadwajekar** [comment]
I would like to work on this...

**Comment by AhmedAbdulKarim** [comment]
how to be assigned to this?

**Comment by virajprabhu** [comment]
@prasadwajekar @AhmedAbdulKarim You can try importing popular models from the Caffe Model Zoo, and comment on this thread with the status (success/fail). If it fails and you'd like to add support for the missing layer(s) required to get it to work, please submit a PR!

**Comment by Ram81** [comment]
@virajprabhu @utsavgarg "ResNets: Deep Residual Networks from MSRA at ImageNet and COCO 2015" doesn't currently get loaded in fabrik can I add support for it?

**Comment by utsavgarg** [comment]
@Ram81 ResNet-101 is already there in the Fabrik Zoo and it loads fine. Which model were you trying ?
![image](https://user-images.githubusercontent.com/11680179/30362067-a3e17bfa-988c-11e7-8af8-6b3b2f00c3fd.png)

**Comment by Ram81** [comment]
@utsavgarg I tried ResNet-101-deploy.prototxt from https://github.com/KaimingHe/deep-residual-networks/tree/master/prototxt

**Comment by utsavgarg** [comment]
@ram81 you will need to change the format of the input layer in that prototxt.

**Comment by Ram81** [comment]
Okay understood I'll try and find which one doesn't work & ask further

**Comment by Ram81** [comment]
@utsavgarg should I also report which one already works so that we can add it to Fabrik/Zoo?

**Comment by JPJPJPOPOP** [comment]
These two don't work due to being in the old Caffe format:
https://github.com/RankingCNN/Using-Ranking-CNN-for-Age-Estimation/blob/master/basic_16to66/deploy_basic.prototxt
https://gist.github.com/mavenlin/d802a5849de39225bcc6#file-train_val-prototxt

Will try updating them to see if they work.

**Comment by JPJPJPOPOP** [comment]
Finished updating both:
RankingCNN: https://gist.github.com/JPJPJPOPOP/6ed94b737a45da81fbc55ce912d6da2a

NINImageNet: https://gist.github.com/JPJPJPOPOP/b8d9f5a1c4cd1bbe624f664f1b85d9bb
