### ISSUE TITLE
Zero parameter count

### ISSUE THREAD

**Issue by thatbrguy** [Cloud-CV/Fabrik#302]
Found another rather weird 0 parameter count issue. 

**Steps to reproduce:**
1. Open fabrik.cloudcv.org, import VGG16 from model zoo.
2. Export model to caffe.
3. Open a new tab, open a fresh fabrik website, import the prototxt file. Params count should be normal. Obtain the share link.
4. Use the share link in a new tab. You should see a zero parameter count. Exporting works fine for VGG, but just says "Error" for Keras for Squeezenet.

Verified the same behavior for a bunch of models.

**Comment by Ram81** [comment]
@thatbrguy I think I know why is this happening, can you let me handle this it is an issue in keras export part

**Comment by thatbrguy** [comment]
@Ram81 Sure thing

**Comment by Ram81** [comment]
@thatbrguy this issue was handled right!
can you close this

**Comment by thatbrguy** [comment]
@Ram81 Ah my bad, I didn't verify if it was fixed so I left it open. Issue seems to be resolved, closing it now.
