### ISSUE TITLE
help！

### ISSUE THREAD

**Issue by zhuhuilong** [Cloud-CV/Fabrik#330]
![image](https://user-images.githubusercontent.com/34827959/37387012-c380c018-2795-11e8-8a69-fa6b71ce3b28.png)
![image](https://user-images.githubusercontent.com/34827959/37387036-de778d02-2795-11e8-8e96-87d2c8300560.png)

**Comment by thatbrguy** [comment]
@zhuhuilong Looks like an installation issue. Please ask such queries in our [gitter channel](https://gitter.im/Cloud-CV/Fabrik).

**Comment by zhuhuilong** [comment]
you should  update your code

**Comment by utsavgarg** [comment]
@zhuhuilong Please ask setup related queries on our [Gitter](https://gitter.im/Cloud-CV/Fabrik) channel.
