### ISSUE TITLE
Export from Tensorflow

### ISSUE THREAD

**Issue by hwq2017** [Cloud-CV/Fabrik#332]
I want to export the model of the googlenet network under the tensorflow framework, but always make the error: "Cannot convert 14(LRN),19(LRN) to Keras".

**Comment by Ram81** [comment]
@hwq2017 currently we don't provide support for LRN layer in keras and tensorflow uses keras as a backend for export.

**Comment by thatbrguy** [comment]
You could checkout PR #287 if you want to work on it.

**Comment by Ram81** [comment]
@hwq2017 support for LRN is added in #356.

Closing this.
