### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by abrad1212** [Cloud-CV/Fabrik#334]
Getting a `504 Gateway Time-out`

Is this just me?

![image](https://user-images.githubusercontent.com/9399948/37624774-5b37befc-2b97-11e8-8e53-149a6c1e536b.png)

**Comment by deshraj** [comment]
@abrad1212 thanks for reporting. We are in process of shifting the website. So, it will be down for sometime.

**Comment by abrad1212** [comment]
@deshraj Well that sucks! Any time frame of when the website will be back up? Also, I'm running Windows any supported way to get a local instance of this running on there... I have gotten to a point where I need to install Caffe to my conda environment and have the prebuilt Caffe binaries, do you know where to install them?
