### ISSUE TITLE
from views import index, calculate_parameter, fetch_layer_shape ImportError: No module named 'views'

### ISSUE THREAD

**Issue by bogireddytejareddy** [Cloud-CV/Fabrik#337]
This error is occurring during 'python manage.py makemigrations caffe_app' step in the installation process.

File "/home/bogireddy/Workspace/Fabrik/ide/urls.py", line 5, in <module>
    from views import index, calculate_parameter, fetch_layer_shape
ImportError: No module named 'views'

**Comment by thatbrguy** [comment]
@bogireddytejareddy You're using Python 3. Fabrik runs on Python 2.7. Reinstall Fabrik on a python 2.7 environment. 

It's an installation issue, please ask such questions in the [gitter channel](https://gitter.im/Cloud-CV/Fabrik).

**Comment by bogireddytejareddy** [comment]
I am new to this. Thank you.
