### ISSUE TITLE
No support for Linear Activation

### ISSUE THREAD

**Issue by MuLx10** [Cloud-CV/Fabrik#340]
![image](https://user-images.githubusercontent.com/23444642/39081617-6433f4dc-4562-11e8-8c45-1c597f3d04f5.png)

Current keras app does not support linear activation

**Comment by sd1998** [comment]
@MuLx10 Are you still working on this. If not I would like to work on this issue.

**Comment by sashank27** [comment]
@MuLx10 @RishabhJain2018 I would like to work on this, if it is available

**Comment by Ram81** [comment]
@sashank27 sure you can go ahead
