### ISSUE TITLE
psycopg2 import error

### ISSUE THREAD

**Issue by yashdusing** [Cloud-CV/Fabrik#375]
Steps to recreate bug (This issue is probably due to the newer Bionic 18.04 release since I never encountered this issue on 16.04, also this is only for local setup & not for Docker)->
1. Followed steps till makemigrations
2.
![screenshot_20180824_115413](https://user-images.githubusercontent.com/19976688/44568839-0d027d00-a796-11e8-9240-1893153c0fcd.png)

Solution ->
1. pip uninstall psycopg2
2. pip install pyscopg2

Edit : There will be a postgresql error after doing this. Just change the HOST to localhost, USER to admin, PASSWORD to fabrik in the settings/dev.py and that should fix it.

**Comment by darthgera123** [comment]
Hi i would like to work on this issue

**Comment by Ram81** [comment]
Closing this
