### ISSUE TITLE
Issue in building a docker. Facing an Issue - You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by 2007anu** [Cloud-CV/Fabrik#384]
Hi,

 I am following the Installation Instructions under Docker and faced issue while using docker-compose up --build. I am using linux environment to build this docker. Attached is the screenshot as well as error log.

ERROR in ./~/entities/maps/legacy.json
reactjs    | Module parse failed: /code/node_modules/entities/maps/legacy.json Unexpected token (1:9)
reactjs    | You may need an appropriate loader to handle this file type.
reactjs    | SyntaxError: Unexpected token (1:9)
reactjs    |     at Parser.pp$4.raise (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
reactjs    |     at Parser.pp.unexpected (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
reactjs    |     at Parser.pp.semicolon (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
reactjs    |     at Parser.pp$1.parseExpressionStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
reactjs    |     at Parser.pp$1.parseBlock (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
reactjs    |     at Parser.pp$1.parseTopLevel (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
reactjs    |     at Parser.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
reactjs    |     at Object.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
reactjs    |     at Parser.parse (/code/node_modules/webpack/lib/Parser.js:902:15)
reactjs    |     at NormalModule.<anonymous> (/code/node_modules/webpack/lib/NormalModule.js:104:16)
reactjs    |     at NormalModule.onModuleBuild (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
reactjs    |     at nextLoader (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
reactjs    |     at /code/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
reactjs    |     at Storage.finished (/code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
reactjs    |     at /code/node_modules/graceful-fs/graceful-fs.js:78:16
reactjs    |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
reactjs    |  @ ./~/htmlparser2/lib/Tokenizer.js 5:16-52
reactjs    |
reactjs    | ERROR in ./~/entities/maps/xml.json
reactjs    | Module parse failed: /code/node_modules/entities/maps/xml.json Unexpected token (1:6)
reactjs    | You may need an appropriate loader to handle this file type.
reactjs    | SyntaxError: Unexpected token (1:6)
reactjs    |     at Parser.pp$4.raise (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
reactjs    |     at Parser.pp.unexpected (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
reactjs    |     at Parser.pp.semicolon (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
reactjs    |     at Parser.pp$1.parseExpressionStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
reactjs    |     at Parser.pp$1.parseBlock (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
reactjs    |     at Parser.pp$1.parseTopLevel (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
reactjs    |     at Parser.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
reactjs    |     at Object.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
reactjs    |     at Parser.parse (/code/node_modules/webpack/lib/Parser.js:902:15)
reactjs    |     at NormalModule.<anonymous> (/code/node_modules/webpack/lib/NormalModule.js:104:16)
reactjs    |     at NormalModule.onModuleBuild (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
reactjs    |     at nextLoader (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
reactjs    |     at /code/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
reactjs    |     at Storage.finished (/code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
reactjs    |     at /code/node_modules/graceful-fs/graceful-fs.js:78:16
reactjs    |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
reactjs    |  @ ./~/htmlparser2/lib/Tokenizer.js 6:16-49
reactjs    |
reactjs    | ERROR in ./~/entities/maps/entities.json
reactjs    | Module parse failed: /code/node_modules/entities/maps/entities.json Unexpected token (1:9)
reactjs    | You may need an appropriate loader to handle this file type.
reactjs    | SyntaxError: Unexpected token (1:9)
reactjs    |     at Parser.pp$4.raise (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
reactjs    |     at Parser.pp.unexpected (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
reactjs    |     at Parser.pp.semicolon (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
reactjs    |     at Parser.pp$1.parseExpressionStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
reactjs    |     at Parser.pp$1.parseBlock (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
reactjs    |     at Parser.pp$1.parseTopLevel (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
reactjs    |     at Parser.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
reactjs    |     at Object.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
reactjs    |     at Parser.parse (/code/node_modules/webpack/lib/Parser.js:902:15)
reactjs    |     at NormalModule.<anonymous> (/code/node_modules/webpack/lib/NormalModule.js:104:16)
reactjs    |     at NormalModule.onModuleBuild (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
reactjs    |     at nextLoader (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
reactjs    |     at /code/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
reactjs    |     at Storage.finished (/code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
reactjs    |     at /code/node_modules/graceful-fs/graceful-fs.js:78:16
reactjs    |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
reactjs    |  @ ./~/htmlparser2/lib/Tokenizer.js 4:16-54
reactjs    |
reactjs    | ERROR in ./~/entities/maps/decode.json
reactjs    | Module parse failed: /code/node_modules/entities/maps/decode.json Unexpected token (1:4)
reactjs    | You may need an appropriate loader to handle this file type.
reactjs    | SyntaxError: Unexpected token (1:4)
reactjs    |     at Parser.pp$4.raise (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
reactjs    |     at Parser.pp.unexpected (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
reactjs    |     at Parser.pp.semicolon (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
reactjs    |     at Parser.pp$1.parseExpressionStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
reactjs    |     at Parser.pp$1.parseBlock (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
reactjs    |     at Parser.pp$1.parseStatement (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
reactjs    |     at Parser.pp$1.parseTopLevel (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
reactjs    |     at Parser.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
reactjs    |     at Object.parse (/code/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
reactjs    |     at Parser.parse (/code/node_modules/webpack/lib/Parser.js:902:15)
reactjs    |     at NormalModule.<anonymous> (/code/node_modules/webpack/lib/NormalModule.js:104:16)
reactjs    |     at NormalModule.onModuleBuild (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
reactjs    |     at nextLoader (/code/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
reactjs    |     at /code/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
reactjs    |     at Storage.finished (/code/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
reactjs    |     at /code/node_modules/graceful-fs/graceful-fs.js:78:16
reactjs    |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

Thanks!
![github_fabrik_issue](https://user-images.githubusercontent.com/10877172/46212040-ae12c380-c352-11e8-93e0-9c4305611c94.jpg)

**Comment by namish800** [comment]
@2007anu run " npm install --save-dev json-loader " and add the following line in the loaders object in webpack.config.js file
>{test: /\.json$/,
        loader: 'json-loader'},

**Comment by 2007anu** [comment]
Thanks @namish800 . 

Even though that issue does not occur, but similar issue still persists related to json-loader.
Also one screenshot is attached which is a Browser link that I opened. It is blank and not showing any error. 

Thanks for all the help.

Please find below the error:

reactjs    |  @ ./~/entities/lib/decode_codepoint.js 1:16-46
reactjs    |
reactjs    | ERROR in ./~/entities/lib/encode.js
reactjs    | Module not found: Error: Cannot resolve module 'json-loader' in /code/node_modules/entities/lib
reactjs    |  @ ./~/entities/lib/encode.js 1:31-58
reactjs    |
reactjs    | ERROR in ./~/entities/lib/encode.js
reactjs    | Module not found: Error: Cannot resolve module 'json-loader' in /code/node_modules/entities/lib
reactjs    |  @ ./~/entities/lib/encode.js 6:32-64
reactjs    |
reactjs    | ERROR in ./~/entities/lib/decode.js
reactjs    | Module not found: Error: Cannot resolve module 'json-loader' in /code/node_modules/entities/lib
reactjs    |  @ ./~/entities/lib/decode.js 1:16-48
reactjs    |
reactjs    | ERROR in ./~/entities/lib/decode.js
reactjs    | Module not found: Error: Cannot resolve module 'json-loader' in /code/node_modules/entities/lib
reactjs    |  @ ./~/entities/lib/decode.js 2:16-46
reactjs    |
reactjs    | ERROR in ./~/entities/lib/decode.js
reactjs    | Module not found: Error: Cannot resolve module 'json-loader' in /code/node_modules/entities/lib
reactjs    |  @ ./~/entities/lib/decode.js 3:16-43
django     | 2018-09-30 16:22:20,364 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
django     | 2018-09-30 16:22:20,365 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
django     | 2018-09-30 16:22:20,366 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
django     | 2018-09-30 16:22:20,366 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receiv
![fabrik](https://user-images.githubusercontent.com/10877172/46259851-e570a400-c4fb-11e8-9009-402bf48ccd75.jpg)
e
django     | 2018-09-30 16:22:20,367 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
django     | 2018-09-30 16:22:20,368 - INFO - server - Using busy-loop synchronous mode on channel layer
django     | 2018-09-30 16:22:20,368 - INFO - server - Listening on endpoint tcp:port=8000:interface=0.0.0.0
django     | [2018/09/30 16:23:00] HTTP GET / 200 [0.04, 172.18.0.1:53926]
django     | [2018/09/30 16:23:00] HTTP GET /static/fonts/font.css 200 [0.05, 172.18.0.1:53928]
django     | [2018/09/30 16:23:00] HTTP GET /static/lib/bootstrap-3.3.6-dist/css/bootstrap.css 200 [0.06, 172.18.0.1:53926]
django     | [2018/09/30 16:23:00] HTTP GET /static/lib/jquery.min.js 200 [0.05, 172.18.0.1:53936]
django     | [2018/09/30 16:23:00] HTTP GET /static/lib/bootstrap-3.3.6-dist/js/bootstrap.js 200 [0.05, 172.18.0.1:53940]
django     | [2018/09/30 16:23:00] HTTP GET /static/lib/jsPlumb-2.1.2-min.js 200 [0.05, 172.18.0.1:53938]
django     | [2018/09/30 16:23:00] HTTP GET /static/bundle/bundle.js 200 [0.06, 172.18.0.1:53944]
django     | [2018/09/30 16:23:04] HTTP GET /static/img/favicon.ico 200 [0.02, 172.18.0.1:53944]
django     | [2018/09/30 16:24:38] HTTP GET / 200 [0.01, 172.18.0.1:53984]
django     | [2018/09/30 16:24:38] HTTP GET /static/lib/bootstrap-3.3.6-dist/css/bootstrap.css 200 [0.04, 172.18.0.1:53984]
django     | [2018/09/30 16:24:38] HTTP GET /static/fonts/font.css 200 [0.04, 172.18.0.1:53986]
django     | [2018/09/30 16:24:38] HTTP GET /static/lib/jquery.min.js 200 [0.02, 172.18.0.1:53998]
django     | [2018/09/30 16:24:38] HTTP GET /static/lib/jsPlumb-2.1.2-min.js 200 [0.03, 172.18.0.1:54002]
django     | [2018/09/30 16:24:38] HTTP GET /static/lib/bootstrap-3.3.6-dist/js/bootstrap.js 200 [0.03, 172.18.0.1:53994]
django     | [2018/09/30 16:24:38] HTTP GET /static/bundle/bundle.js 200 [0.03, 172.18.0.1:54000]

**Comment by Ram81** [comment]
This issue has been fixed in #385
