### ISSUE TITLE
Cloud CV is not opening in Mozilla Firefox

### ISSUE THREAD

**Issue by AdithyaKannan** [Cloud-CV/Fabrik#422]
I tried to open Cloud CV with Firefox but message appears that it is not compatible with your browser.

**Comment by thatbrguy** [comment]
I use firefox and I did not see any such message. Please post the version of firefox you used.

**Comment by Ram81** [comment]
@AdithyaKannan can you post a screenshot to show what is not working on your end?

**Comment by gautamjajoo** [comment]
@AdithyaKannan @Ram81 It works fine for me too.
