### ISSUE TITLE
Docker failed

### ISSUE THREAD

**Issue by alpharomeo7** [Cloud-CV/Fabrik#439]
The error is : 
 Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/libfakeroot_1.20.2-1ubuntu1_amd64.deb  Connection failed [IP: 91.189.88.161 80] 

while setting up the docker

Thanks in advance

**Comment by Ram81** [comment]
@alpharomeo7 this doesn't seem to be an issue on our end. It may be an issue with your network, because docker setup works good on my end. But I'll cross check and get back to you on this.
