### ISSUE TITLE
Automatically parse Caffe Prototxt file to support all the different layers

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Fabrik#44]
Caffe has all the layers and it's layer parameters defined in a prototxt definition. Instead of adding support for layers one by one inside IDE, it will be nice to automatically parse the definition from the master branch of caffe and add support for those layers.

**Requirements:** Understanding caffe's codebase written in C++, Understanding the prototxt structure and familiarily with automated tasks in Javascript to automatically build the layer support into IDE.
- We can first start by parsing the protobuf definitions to identify all the supported layer parameters.
- Identify the mapping between layer and layer parameters
- Identify number of input / output for each layer
- Add them into IDE

**Benefits:** Doing this will ensure that we don't need to actively maintain the IDE repo to in sync with the caffe branch.

**Comment by dexter1691** [comment]
All the layer parameter definitions here: https://github.com/BVLC/caffe/blob/80f44100e19fd371ff55beb3ec2ad5919fb6ac43/src/caffe/proto/caffe.proto

**Comment by dexter1691** [comment]
To identify the number of input / output blobs in each layer, we can query this function: https://github.com/BVLC/caffe/blob/master/include/caffe/layer.hpp#L200-L240

**Comment by venky18** [comment]
I would like to work on it.

**Comment by dexter1691** [comment]
@venky18 This issue is fairly difficult. Feel free to first get familiar with the caffe codebase and get started by first parsing the protobuf definition to identify the parameters. Update your progress here and let's take it from there.

**Comment by venky18** [comment]
@dexter1691  I read about protocol buffers and prototxt file and now i have written a small program to parse the protoxt file and print the different parameters.

**Comment by virajprabhu** [comment]
Fixed in #77, #78, #79.
