### ISSUE TITLE
TensorFlow in requirements.

### ISSUE THREAD

**Issue by achillesrasquinha** [Cloud-CV/Fabrik#51]
I don't think TensorFlow should be part of the requirements.txt. Users could install this separately (or a build script can be written for the same - e.g. a Makefile) since TensorFlow wasn't completely registered under pip (*pip installable*) until their initial version release. This can also help new users of Fabrik to opt for GPU-tensorflow (which requires NVIDIA CUDA and CuDNN installed).

**Comment by utsavgarg** [comment]
fixed in #64

**Comment by achillesrasquinha** [comment]
👍
