### ISSUE TITLE
Fabrik doesn't prevent from creating cyclic graph

### ISSUE THREAD

**Issue by SudarAbisheck** [Cloud-CV/Fabrik#52]
![snap1](https://cloud.githubusercontent.com/assets/6151411/24606589/703d5714-188b-11e7-9190-422c15778bd9.png)
![snap2](https://cloud.githubusercontent.com/assets/6151411/24606590/704f2ae8-188b-11e7-88f3-06b229def11f.png)

When you try to export, it just throws internal server error.

**Comment by virajprabhu** [comment]
@SudarAbisheck Thanks for reporting this. Should be a simple enough check to add. Are you interested in taking this up?

**Comment by virajprabhu** [comment]
@utsavgarg Can you add this check?

**Comment by utsavgarg** [comment]
Issue fixed in PR #74 

![cyclic_1](https://cloud.githubusercontent.com/assets/11680179/26485496/f3918ace-4214-11e7-8381-ed88df39df55.png)
![cyclic_2](https://cloud.githubusercontent.com/assets/11680179/26485499/f48c35f0-4214-11e7-9a01-f75fff569d44.png)
