### ISSUE TITLE
Setup Travis CI and Coveralls

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Fabrik#6]

**Comment by anweshknayak** [comment]
@deshraj do I need to add tensorflow and caffe build to the .travis.yml for now ? or shall I skip that?
And if I add those builds. Where to define the path for tensorflow and caffe to be installed for that script? I took a look at the (https://github.com/Cloud-CV/CloudCV/blob/master/.travis.yml). Shall it be like TOOLS_DIR="$HOME/tools" ?

**Comment by deshraj** [comment]
@anweshknayak yeah. I was going to ask you to refer this file only. You can take inspiration from this file. We can make modifications in the directory structure later. 

Let me know if you need any help. We can discuss on Gitter.

**Comment by devojoyti** [comment]
@anweshknayak @deshraj  Is the task completed ? Can I help ?

**Comment by deshraj** [comment]
Hi @devojoyti, I think @anweshknayak is working on this. Can you please pick some other issue.

**Comment by anweshknayak** [comment]
If anyone wants to pick this up. Please feel free to do so.

**Comment by venky18** [comment]
I am interested in this. I have a question should i use pip or miniconda?

**Comment by venky18** [comment]
thanks for quick reply. Since I am comfortable with pip I will be using  pip.

**Comment by virajprabhu** [comment]
Fixed in #56.
