### ISSUE TITLE
Write unittests 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Fabrik#7]

**Comment by DESHRAJ** [comment]
We can use coverage to write tests in python. For reference, see https://coverage.readthedocs.io/en/coverage-4.1/

**Comment by souravsingh** [comment]
I am interested in working on the issue.

**Comment by deshraj** [comment]
@souravsingh I am glad that you are interested in working on this issue. let me know if you need any help.

**Comment by anweshknayak** [comment]
anyone working on this one ?

**Comment by souravsingh** [comment]
I am working on the issue

**Comment by deshraj** [comment]
I think this issue would be pretty big and working alone on it would take a lot of time. It would be a good idea if we can divide stuff between you guys. Also, we can discuss more on the gitter channel https://gitter.im/Cloud-CV/IDE

**Comment by anweshknayak** [comment]
@souravsingh you working on this ?

**Comment by gauthamzz** [comment]
@anweshknayak @deshraj i would like to also help ?
